#!/bin/bash
t=$(mktemp -t emacs-pager.XXXXXXXXXXXXXX) || exit 1
cat - >> "$t"
echo 'reading into emacs...'
if test -x /Applications/Aquamacs.app/Contents/MacOS/bin/emacsclient; then
    export EDITOR="/Applications/Aquamacs.app/Contents/MacOS/bin/emacsclient"
else
    export EDITOR="/usr/bin/emacsclient"
fi
"$EDITOR" "$t"
rm -f -- "$t"
